sudo: required

services:
  - docker

osx_image: xcode9.3

matrix:
  include:
    - os: osx
      env: TEST_SH=mac_test.sh
    - env: TEST_SH=archlinux_test.sh
    - env: TEST_SH=debian_test.sh
    - env: TEST_SH=fedora_test.sh
    - env: TEST_SH=ubuntu_16_04_test.sh
    - env: TEST_SH=ubuntu_18_04_test.sh
    - env: TEST_SH=linux_sysroot_test.sh

script: "tests/scripts/${TEST_SH}"
